# Generated by Django 3.0.6 on 2020-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cu_number',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
