# Generated by Django 3.0.6 on 2020-06-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_cu_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cu_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='data_sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DataSheet'),
        ),
    ]
